services:
  api:
    build: apps/api
    restart: unless-stopped

  web:
    build: apps/web
    ports:
      - "8080:8080"
    depends_on:
      api:
        condition: service_healthy
    restart: unless-stopped
